// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.23.0
// 	protoc        v3.13.0
// source: protos/sample.proto

package gen_grpc

import (
	context "context"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type Sample struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Sample) Reset() {
	*x = Sample{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_sample_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Sample) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Sample) ProtoMessage() {}

func (x *Sample) ProtoReflect() protoreflect.Message {
	mi := &file_protos_sample_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Sample.ProtoReflect.Descriptor instead.
func (*Sample) Descriptor() ([]byte, []int) {
	return file_protos_sample_proto_rawDescGZIP(), []int{0}
}

type Sample_GetMySampleMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Target_Sample string `protobuf:"bytes,1,opt,name=target_Sample,json=targetSample,proto3" json:"target_Sample,omitempty"`
}

func (x *Sample_GetMySampleMessage) Reset() {
	*x = Sample_GetMySampleMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_sample_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Sample_GetMySampleMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Sample_GetMySampleMessage) ProtoMessage() {}

func (x *Sample_GetMySampleMessage) ProtoReflect() protoreflect.Message {
	mi := &file_protos_sample_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Sample_GetMySampleMessage.ProtoReflect.Descriptor instead.
func (*Sample_GetMySampleMessage) Descriptor() ([]byte, []int) {
	return file_protos_sample_proto_rawDescGZIP(), []int{0, 0}
}

func (x *Sample_GetMySampleMessage) GetTarget_Sample() string {
	if x != nil {
		return x.Target_Sample
	}
	return ""
}

type Sample_MySampleResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Kind string `protobuf:"bytes,2,opt,name=kind,proto3" json:"kind,omitempty"`
}

func (x *Sample_MySampleResponse) Reset() {
	*x = Sample_MySampleResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_sample_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Sample_MySampleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Sample_MySampleResponse) ProtoMessage() {}

func (x *Sample_MySampleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protos_sample_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Sample_MySampleResponse.ProtoReflect.Descriptor instead.
func (*Sample_MySampleResponse) Descriptor() ([]byte, []int) {
	return file_protos_sample_proto_rawDescGZIP(), []int{0, 1}
}

func (x *Sample_MySampleResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Sample_MySampleResponse) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

var File_protos_sample_proto protoreflect.FileDescriptor

var file_protos_sample_proto_rawDesc = []byte{
	0x0a, 0x13, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2f, 0x73, 0x61, 0x6d, 0x70, 0x6c, 0x65, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x08, 0x67, 0x65, 0x6e, 0x5f, 0x67, 0x72, 0x70, 0x63, 0x22,
	0x7f, 0x0a, 0x06, 0x53, 0x61, 0x6d, 0x70, 0x6c, 0x65, 0x1a, 0x39, 0x0a, 0x12, 0x47, 0x65, 0x74,
	0x4d, 0x79, 0x53, 0x61, 0x6d, 0x70, 0x6c, 0x65, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12,
	0x23, 0x0a, 0x0d, 0x74, 0x61, 0x72, 0x67, 0x65, 0x74, 0x5f, 0x53, 0x61, 0x6d, 0x70, 0x6c, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x74, 0x61, 0x72, 0x67, 0x65, 0x74, 0x53, 0x61,
	0x6d, 0x70, 0x6c, 0x65, 0x1a, 0x3a, 0x0a, 0x10, 0x4d, 0x79, 0x53, 0x61, 0x6d, 0x70, 0x6c, 0x65,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x12, 0x0a, 0x04,
	0x6b, 0x69, 0x6e, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6b, 0x69, 0x6e, 0x64,
	0x32, 0x68, 0x0a, 0x0d, 0x53, 0x61, 0x6d, 0x70, 0x6c, 0x65, 0x41, 0x64, 0x61, 0x70, 0x74, 0x65,
	0x72, 0x12, 0x57, 0x0a, 0x0b, 0x47, 0x65, 0x74, 0x4d, 0x79, 0x53, 0x61, 0x6d, 0x70, 0x6c, 0x65,
	0x12, 0x23, 0x2e, 0x67, 0x65, 0x6e, 0x5f, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x53, 0x61, 0x6d, 0x70,
	0x6c, 0x65, 0x2e, 0x47, 0x65, 0x74, 0x4d, 0x79, 0x53, 0x61, 0x6d, 0x70, 0x6c, 0x65, 0x4d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x1a, 0x21, 0x2e, 0x67, 0x65, 0x6e, 0x5f, 0x67, 0x72, 0x70, 0x63,
	0x2e, 0x53, 0x61, 0x6d, 0x70, 0x6c, 0x65, 0x2e, 0x4d, 0x79, 0x53, 0x61, 0x6d, 0x70, 0x6c, 0x65,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x12, 0x5a, 0x10, 0x61, 0x64,
	0x61, 0x70, 0x74, 0x65, 0x72, 0x2f, 0x67, 0x65, 0x6e, 0x5f, 0x67, 0x72, 0x70, 0x63, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_protos_sample_proto_rawDescOnce sync.Once
	file_protos_sample_proto_rawDescData = file_protos_sample_proto_rawDesc
)

func file_protos_sample_proto_rawDescGZIP() []byte {
	file_protos_sample_proto_rawDescOnce.Do(func() {
		file_protos_sample_proto_rawDescData = protoimpl.X.CompressGZIP(file_protos_sample_proto_rawDescData)
	})
	return file_protos_sample_proto_rawDescData
}

var file_protos_sample_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_protos_sample_proto_goTypes = []interface{}{
	(*Sample)(nil),                    // 0: gen_grpc.Sample
	(*Sample_GetMySampleMessage)(nil), // 1: gen_grpc.Sample.GetMySampleMessage
	(*Sample_MySampleResponse)(nil),   // 2: gen_grpc.Sample.MySampleResponse
}
var file_protos_sample_proto_depIdxs = []int32{
	1, // 0: gen_grpc.SampleAdapter.GetMySample:input_type -> gen_grpc.Sample.GetMySampleMessage
	2, // 1: gen_grpc.SampleAdapter.GetMySample:output_type -> gen_grpc.Sample.MySampleResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_protos_sample_proto_init() }
func file_protos_sample_proto_init() {
	if File_protos_sample_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_protos_sample_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Sample); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_sample_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Sample_GetMySampleMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_sample_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Sample_MySampleResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_protos_sample_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_protos_sample_proto_goTypes,
		DependencyIndexes: file_protos_sample_proto_depIdxs,
		MessageInfos:      file_protos_sample_proto_msgTypes,
	}.Build()
	File_protos_sample_proto = out.File
	file_protos_sample_proto_rawDesc = nil
	file_protos_sample_proto_goTypes = nil
	file_protos_sample_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// SampleAdapterClient is the client API for SampleAdapter service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type SampleAdapterClient interface {
	GetMySample(ctx context.Context, in *Sample_GetMySampleMessage, opts ...grpc.CallOption) (*Sample_MySampleResponse, error)
}

type sampleAdapterClient struct {
	cc grpc.ClientConnInterface
}

func NewSampleAdapterClient(cc grpc.ClientConnInterface) SampleAdapterClient {
	return &sampleAdapterClient{cc}
}

func (c *sampleAdapterClient) GetMySample(ctx context.Context, in *Sample_GetMySampleMessage, opts ...grpc.CallOption) (*Sample_MySampleResponse, error) {
	out := new(Sample_MySampleResponse)
	err := c.cc.Invoke(ctx, "/gen_grpc.SampleAdapter/GetMySample", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SampleAdapterServer is the server API for SampleAdapter service.
type SampleAdapterServer interface {
	GetMySample(context.Context, *Sample_GetMySampleMessage) (*Sample_MySampleResponse, error)
}

// UnimplementedSampleAdapterServer can be embedded to have forward compatible implementations.
type UnimplementedSampleAdapterServer struct {
}

func (*UnimplementedSampleAdapterServer) GetMySample(context.Context, *Sample_GetMySampleMessage) (*Sample_MySampleResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetMySample not implemented")
}

func RegisterSampleAdapterServer(s *grpc.Server, srv SampleAdapterServer) {
	s.RegisterService(&_SampleAdapter_serviceDesc, srv)
}

func _SampleAdapter_GetMySample_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Sample_GetMySampleMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SampleAdapterServer).GetMySample(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/gen_grpc.SampleAdapter/GetMySample",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SampleAdapterServer).GetMySample(ctx, req.(*Sample_GetMySampleMessage))
	}
	return interceptor(ctx, in, info, handler)
}

var _SampleAdapter_serviceDesc = grpc.ServiceDesc{
	ServiceName: "gen_grpc.SampleAdapter",
	HandlerType: (*SampleAdapterServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetMySample",
			Handler:    _SampleAdapter_GetMySample_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "protos/sample.proto",
}
